### ISSUE TITLE
Map not displayed

### ISSUE THREAD

**Issue by jaks6** [medalionk/android_project#2]
When switching to the Map tab on my Nexus 5, the view is rendered as a grey area.

Although I don't have access to the Logcat right now, I suspect this problem is related to Google Maps API keys and their management. Try to see if you can re-create this issue, for example by freshly installing the app from Google Play Store on your phone.

**Comment by ayblaq** [comment]
Yes, this is related to Google Maps API

**Comment by jaks6** [comment]
Have you seen this material? https://developers.google.com/maps/documentation/android-api/signup#detailed-guides

I believe applying the restricted mode for the Maps API Project and the relevant fingerprints are important.

**Comment by medalionk** [comment]
Fixed. 

The problem was that we used the debug.keystore SHA1 applying the restriction which was different from the one used in signing the final app. 

But we have another problem, the location of events are most times names of business, for example "Club Illusion" and sometimes addresses. For the addresses, we tried using Google Geocoding API to get the location, while for the business names we tried Google Places API to get the location. But both of these APIs have request quotas, only Google Map API is unlimited. So now the map just shows Tartu.
